# Generated by Django 5.2 on 2025-04-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiumuser',
            options={'verbose_name': 'کاربر ویژه', 'verbose_name_plural': 'کاربرهای ویژه'},
        ),
    ]
