# Generated by Django 5.2 on 2025-04-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_premiumuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiumuser',
            options={'verbose_name': 'نوع حساب کاربری'},
        ),
    ]
